### ISSUE TITLE
Lost access to plugin (not work)

### ISSUE THREAD

**Issue by aToshik** [figma-plus/installer#10]
Hello,
First of all, thanks for your work. This is very useful, and it has long been a part of my daily work with figma.

I used your plugin injector and everything was ok.

Till today. This morning I did not find the plug-in icon. 
![image](https://user-images.githubusercontent.com/48434714/54113104-42984c00-43f0-11e9-9b99-e49bbc29b97d.png)

And also I lost access to it through the context menu.
![image](https://user-images.githubusercontent.com/48434714/54113120-4e840e00-43f0-11e9-9118-28634e5f51f3.png)

I tried to reinstall, I did not work.
![image](https://user-images.githubusercontent.com/48434714/54113152-5e035700-43f0-11e9-8d94-87f8aa2e414a.png)

**Comment by aToshik** [comment]
I deleted the figma. Removed the injector. I made a restart.
Established figma. Install the injector.
![image](https://user-images.githubusercontent.com/48434714/54114296-c0f5ed80-43f2-11e9-90a6-72af3be5b5a3.png)
![image](https://user-images.githubusercontent.com/48434714/54114306-ca7f5580-43f2-11e9-9e4e-ef6f302ac373.png)

Still bad.

**Comment by cdes** [comment]
Hey @aToshik ! 👋🏼

Thank you for your kind words.  First of all, please allow me to apologize for the inconvenience. 🙏🏼

Figma plus is not released officially yet, it's still work-in-progress and it was bound to break sooner or later.  I'll notify you once we reach a stable release.

Again, I'm sorry.
