### ISSUE TITLE
Figma Plus stopped working

### ISSUE THREAD

**Issue by romashamin** [figma-plus/installer#11]
Hey, at first thank you, great work!

The issue. I have installed Figma Plus and it worked great at first. I activated dev mode, started to play with plugin boilerplate. But, after weekend I noticed the icon at right of the toolbar disappeared along with menu item.

I tried to uninstall and install Figma Plus a few times — nothing. Even Figma stopped working with this message:

<img width="287" alt="Screenshot 2019-03-12 18 22 55" src="https://user-images.githubusercontent.com/1148914/54214336-174c5480-44f7-11e9-8a5a-0d8317f84477.png">

Also tried to restart macOS — nothing. So I had to reinstall Figma `¯\_(ツ)_/¯`

macOS Mojave 10.14.3
Figma Desktop App release 68

How can I help with that?

**Comment by aToshik** [comment]
@romashamin 
https://github.com/figma-plus/installer/issues/10

**Comment by romashamin** [comment]
@aToshik uh, thank you! I didn’t check closed issues.

**Comment by MurodAkmalovich** [comment]
@romashamin @aToshik hello, the same problem with me how can I fix it?

**Comment by MurodAkmalovich** [comment]
![Capture](https://user-images.githubusercontent.com/52958167/61285961-46dbd800-a7db-11e9-9336-8ef8f8c4ea17.JPG)

**Comment by MurodAkmalovich** [comment]
I use Windows 10
